DROP TABLE IF EXISTS tbl__VPS;

--VPS Table
CREATE TABLE IF NOT EXISTS tbl__VPS (
    ID INTEGER PRIMARY KEY,
    Name TEXT NOT NULL,
    CategoryID INTEGER NOT NULL,
    Status INTEGER NOT NULL
);
--VPS Value
INSERT INTO tbl__VPS (ID, Name, CategoryID, Status)
VALUES (1, 'CHIP01', 1, 1)